### ISSUE TITLE
Server resource packs crash game on 1.8

### ISSUE THREAD

**Issue by TheKodeToad** [ReplayMod/ReplayMod#695] opened 2022-03-03 19:07 UTC
This is caused by an invalid cast to IDownloadingPackFinder, because MixinDownloadingPackFinder isn't applied.

**Comment by Johni0702** [comment] 2022-03-05 08:44
Duplicate of #86

**Closed by Johni0702** 2022-03-05 08:44 UTC

**Comment by TheKodeToad** [comment] 2022-03-10 08:36
Ah. I didn't see that because I was looking through open issues.
