### ISSUE TITLE
When "Show FPS" is on in Optifine it shows up in Video

### ISSUE THREAD

**Issue by Sebast04** [ReplayMod/ReplayMod#555] opened 2021-08-01 20:07 UTC
When "Show FPS" is on in Optifine / Options -->Video Settings --> Other, FPS Information is also displayed in the rendered Video
w Replaymod 1.17.1 and newest optifine and optifabric version, could name exact version if relevant
screenshot provided below
![Screenshot 2021-08-01 220309](https://user-images.githubusercontent.com/77791868/127783995-a6893e81-ff50-4eb9-b4b0-df23cdeada4f.png)

**Comment by RaderRMT** [comment] 2021-08-01 20:08
wild guess, that will be a wontfix.

**Comment by dbrighthd** [comment] 2021-08-01 20:38
This happens wi the simple HUD mod as well

**Comment by Johni0702** [comment] 2021-08-15 10:56
Optifine does not render this text as part of the regular HUD, so this showing in the rendered video is working as intended (in the same way post-processing effects are supposed to show in the rendered video). For this to be fixed, Optifine simply has to render the text as part of the regular HUD (just like e.g. the side scoreboard, the chat or the hotbar).

> This happens wi the simple HUD mod as well

Make sure you're not using an old version and then open a separate issue listing the exact versions you're using and where you got them from. I haven't tried it myself but from just looking at [the source code](https://github.com/TGMDevelopment/SimpleHUD-Forge/tree/1.9.2) this should not happen with that mod.

**Closed by Johni0702** 2021-08-15 10:56 UTC
