### ISSUE TITLE
"Render All" Button is Grayed-Out

### ISSUE THREAD

**Issue by redstonecreeper8** [ReplayMod/ReplayMod#466] opened 2021-01-22 02:37 UTC
I have several camera paths stored in my render queue; however, the option to render all of them seems permanently disabled. This defeats the primary purpose of the queue. Is this a bug or is there something I'm doing incorrectly? I can't find any information about this behavior online.

**Comment by RaderRMT** [comment] 2021-01-22 06:48
Select all elements in the queue then press the Render All button

**Comment by Johni0702** [comment] 2021-01-22 09:51
Duplicate of #447

**Closed by Johni0702** 2021-01-22 09:51 UTC
