### ISSUE TITLE
Buttons not there

### ISSUE THREAD

**Issue by aflacc** [ReplayMod/ReplayMod#445] opened 2020-12-21 01:18 UTC
All the buttons the mod adds (start/stop recording, the title screen buttons etc.) are not here. I am using v2.5.1 for 1.16.4 I have the following mods also installed:
![image](https://user-images.githubusercontent.com/60161366/102729842-42c4bb80-42e7-11eb-9cc2-365535543f8f.png)
any ideas why they are not showing? I can access the config and stuff via the ModMenu mod

**Comment by RaderRMT** [comment] 2020-12-21 09:34
Can you try without optifine & optifabric?

**Comment by aflacc** [comment] 2020-12-27 00:48
I'll give it a shot

**Comment by aflacc** [comment] 2020-12-27 00:50
![image](https://user-images.githubusercontent.com/60161366/103161678-616cfb80-479a-11eb-9c14-27775f5af4f2.png)
Still not working

**Comment by Johni0702** [comment] 2020-12-27 01:15
Try without any other mods, then add them back one by one such that you can isolate which one is causing the issue.
Please then also confirm that it is only the ReplayMod and that other mod which trigger the issue (by again removing everything else) and not a combination of three (or more) mods.

**Comment by aflacc** [comment] 2021-01-07 18:42
Update: It appears whenever i have 5 or less mods active. I literally added worldedit makign it 6 and it stopped showing up

**Comment by Johni0702** [comment] 2021-10-10 19:20
> this same thing happens with modmenu on fabric but at least it shows settings button inside the modmenu, just not start/stop recording

No, it does not. There have been tens of thousands of people using RM with ModMenu (including myself) across all versions we support and no one has ever had this issue with ModMenu. Please open your own issue and provide more information there.

I'm closing this issue because OP did not provided enough information for anyone to reproduce this. If this is still happening, please carefully re-read my previous message and then open a new issue for it, including all the necessary info in there.

**Closed by Johni0702** 2021-10-10 19:20 UTC
Labels: bug, needs more information
