### ISSUE TITLE
Strange rendering window on MacOS

### ISSUE THREAD

**Issue by ceiri** [ReplayMod/ReplayMod#696] opened 2022-03-03 19:38 UTC
When rendering on MacOS, it shows the below window, with what seems to be the top of the QuickTime icon. This seems to be a longstanding issue but still has not been fixed.

<img width="1440" alt="Screenshot 2022-03-03 at 19 34 52" src="https://user-images.githubusercontent.com/57523771/156639513-142a6ecb-cde5-4548-a69f-5593e4141960.png">

**Comment by cenabach69** [comment] 2022-03-03 19:39
Note: the amethyst blocks is a custom resource pack

**Comment by bela333** [comment] 2022-03-03 20:19
[retiNO](https://www.curseforge.com/minecraft/mc-mods/retino) might help with solving this problem.

**Comment by Johni0702** [comment] 2022-03-05 08:45
Duplicate of #338

**Closed by Johni0702** 2022-03-05 08:45 UTC
