### ISSUE TITLE
Crash on saving file when I use modded worldtype

### ISSUE THREAD

**Issue by 1103kash** [ReplayMod/ReplayMod#113] opened 2020-03-28 00:30 UTC
I cannot save the file when I recorded it in modded worldtype.

**Comment by Johni0702** [comment] 2020-03-28 00:36
Duplicate of #69

**Closed by Johni0702** 2020-03-28 00:36 UTC

**Comment by 1103kash** [comment] 2020-03-28 02:01
hi there, i would like to rewrite worldtype in MagicValues in Replaymod.
could you give me source code of magicvalues by some pay?

2020年3月28日(土) 9:36 Jonas Herzig <notifications@github.com>:
