### ISSUE TITLE
Crash on minecraft 1.18.1

### ISSUE THREAD

**Issue by bubble13699** [ReplayMod/ReplayMod#699] opened 2022-03-06 11:37 UTC
So my reply mod made the game crash when starting. at first the game was completely fine, but when i close my game and tried try to start it again...it just crashed.
[crash-2022-03-06_20.30.34-client.txt](https://github.com/ReplayMod/ReplayMod/files/8192447/crash-2022-03-06_20.30.34-client.txt)
 Please help.

**Comment by Johni0702** [comment] 2022-03-06 11:45
See https://github.com/ReplayMod/ReplayMod/issues/683#issuecomment-1039931076

**Comment by Johni0702** [comment] 2022-03-06 11:45
Duplicate of #682

**Closed by Johni0702** 2022-03-06 11:45 UTC

**Comment by Kepler-17c** [comment] 2022-03-06 11:49
TLauncher is illegal and not supported

**Comment by bubble13699** [comment] 2022-03-06 12:21
thanks, it is working fine now
