### ISSUE TITLE
Missing map art in video render

### ISSUE THREAD

**Issue by beskhu3epnm** [ReplayMod/ReplayMod#109] opened 2020-03-23 12:52 UTC
Hello. I noticed map art is not rendered while in spectate mode from the Replay Mod. When you look at a map, it is blank. This is really unfortunate for me, and I'm wondering if there's a way to fix this. I would have liked to ask on the forums, but it appears I'm able able to register there for some reason. The registration button is nowhere to be found.
![blank-map](https://user-images.githubusercontent.com/45117360/77318500-14d52b00-6d05-11ea-980a-74e92744f091.jpg)

**Comment by Johni0702** [comment] 2020-03-23 15:10
Which Minecraft and ReplayMod versions were you using?

**Comment by beskhu3epnm** [comment] 2020-03-23 20:24
I am using `replaymod-1.14.4-2.2.0-b7` on `fabric-loader-0.7.8+build.184-1.14.4`, with `fabric-api-0.4.1+build.245-1.14.jar` in the mod folder.

**Comment by beskhu3epnm** [comment] 2020-03-23 21:02
Also a side-issue I will bring to your attention. Using the most recent Fabric API (fabric-api-0.4.3+build.247-1.14.jar) causes text GUI problems. I downgraded to the Fabric API version above, and the text displays fine again.
![Screenshot_2020-03-23_20-48-14](https://user-images.githubusercontent.com/45117360/77362719-54256b00-6d49-11ea-84dd-70af386decfc.png)
Aside from the Fabric API, I believe I'm using the most up-to-date versions.

**Comment by Johni0702** [comment] 2020-03-23 21:13
The text issue is a known one, see https://github.com/ReplayMod/ReplayMod/issues/101 for workarounds.

**Comment by beskhu3epnm** [comment] 2020-03-23 21:52
Is there a workaround for the map not rendering? Such as using an older version of Replay Mod? I'm surprised nobody has made you aware of it.

**Comment by Johni0702** [comment] 2020-03-23 21:58
None that I know of. This is the first time I hear about it (may be that it just appear with the 1.14 version).
Tbh I wouldn't even know of the top of my head how it could break like that. Someone will have to take a close look at it. However since I'm currently not actively working on the RM, it might be some time before that happens.

**Comment by beskhu3epnm** [comment] 2020-03-23 22:26
Okay no worries. Thanks for the response.

**Comment by beskhu3epnm** [comment] 2020-03-23 23:19
For clarification, the map art does not appear in the Replay Mod editor also, so it's not a video rendering problem.

**Comment by Gerrygames** [comment] 2020-03-29 14:37
Are you spectating the player that recorded the replay? The server only sends map data if the map is in an item frame or to the player that is holding a map. And the replay mod can obviously only record what the client receives.

**Comment by beskhu3epnm** [comment] 2020-03-30 05:48
I recorded myself playing the game occasionally looking at map art I was holding, and in the Replay Editor went to spectate myself and then rendered it. I didn't notice in the Replay Editor that the map art was blank, only after rendering the video. The map art was present in the game of course, just not in the Editor.

See the video here: https://youtu.be/ned8JP5n-n0?t=44

**Comment by Johni0702** [comment] 2020-04-08 21:39
Upon close inspection, this appears to be a bug in the Start/Stop/Pause/Resume recording feature. To reproduce it, I need to make use of that feature during recording at least once.
So one can work around the issue by not using that feature.

The code implementing that feature has been completely re-written in the process of updating to 1.15 because it contained various fundamental flaws. I can no longer reproduce the issue with the new version (a 1.14.4 RM jar built from the `1.15` branch), so whatever the issue was, it probably got fixed as a side-effect of that re-write.
I'll close this issue once the new version gets a proper release.

**Comment by beskhu3epnm** [comment] 2020-04-09 06:38
Thank you, that solution does the trick.

**Closed** 2020-05-08 11:45 UTC
Labels: bug
