### ISSUE TITLE
crash when editing (1.16.3)

### ISSUE THREAD

**Issue by ro-mod-dev** [ReplayMod/ReplayMod#395] opened 2020-10-23 12:54 UTC
when I'm editing a video, taken in solo-mod and I return over the time, my crash, but, when I'm in multiplayer this doesn't happen,you will find here my crash report, hope this can help you to be more stabble.

[crash-2020-10-23_14.42.00-client.txt](https://github.com/ReplayMod/ReplayMod/files/5429524/crash-2020-10-23_14.42.00-client.txt)

**Comment by Johni0702** [comment] 2020-10-24 09:19
Duplicate of #387

**Closed by Johni0702** 2020-10-24 09:19 UTC
