### ISSUE TITLE
Modded Mobs Disappear When Rewinding

### ISSUE THREAD

**Issue by Kepler-17c** [ReplayMod/ReplayMod#681] opened 2022-02-13 04:00 UTC
Reported by Onidanku#4336 https://discord.com/channels/708304818829262910/709108200632483900/942250257088131094

Log: https://cdn.discordapp.com/attachments/709108200632483900/942264813676015666/latest.log

The entities stay while replaying and skipping forward, but vanish when skipping backwards with the "loading world" screen.  
They also don't show up in the rendered video.

**Comment by Johni0702** [comment] 2022-02-13 07:58
Sounds very much like #674, will double check once that's fixed.

**Comment by Johni0702** [comment] 2022-03-02 17:58
Had some trouble installing that mod, so I wasn't able to double check but it very much looks like the same thing, so I'm gonna close this as a duplicate for now. Can always be re-opened if it turns out that there's more to it.

**Comment by Johni0702** [comment] 2022-03-02 17:58
Duplicate of #674

**Closed by Johni0702** 2022-03-02 17:58 UTC
Labels: bug, compatibility
