### ISSUE TITLE
Visual Glitch in Mac in Exporting Screen

### ISSUE THREAD

**Issue by TrollPotter3587** [ReplayMod/ReplayMod#698] opened 2022-03-05 09:56 UTC
When I export the file and it is in the processing page, there is a glitch. This glitch doesn't occur in my Windows Laptop that I use. I also tried using full screen (Minecraft settings one and the mac window full screen one). Another thing is, the buttons also work. But it is just that I can't see them and it is in the correct place if the visual glitch wan't there.
Here's the vid to show the glitch. 
https://youtu.be/BTXTtY1FE4Q

**_Other info (if needed [just in case])_**

Macbook **Pro** - _Mac OS Monterey_. This glitch was also in Mac OS Big Sur(I think)

I used **MultiMC** to launch Minecraft. But this glitch was also occurring in **normal Fabric Minecraft** launch.

MODS: Fabric - **MultiMC**
 - 3D Skin Layers
 - Better Dropped Items
 - Fabric API
 - Hydrogen
 - Iris
 - Lithium
 - MinecraftCaoed Mod
 - Mod Menu
 - NotEnoughAnimations
 - PHOSPHOR
 - Replay Mod 
 - Sodium **(Downloaded from the Replay Mod website)**
 - wthit

MODS: Fabric - **Normal Launcher**
 - Fabric API
 - Replay Mod
 - Hydrogen
 - Lithium
 - Logical_Zoom
 - Malilib Library
 - Mod Menu
 - Phosphor
 - Shulker Box Tooltip
 - Sodium **(Downloaded from the Replay Mod website)**
 - Tooltip Fix
 - Tweakeroo
 - Voicechat
 - Worldedit
 - wthit

Please fix this problem.

**Comment by Johni0702** [comment] 2022-03-05 10:25
Duplicate of #338

**Closed by Johni0702** 2022-03-05 10:25 UTC

**Comment by TrollPotter3587** [comment] 2022-03-05 10:29
Wait so is this fixed or what

**Comment by TrollPotter3587** [comment] 2022-03-05 10:30
> So is this fixed or what

**Comment by Johni0702** [comment] 2022-03-05 10:44
No, this has already been reported, and if you look at the issue I linked, it's still open and assigned to the upcoming 2.6.4 update.

**Comment by TrollPotter3587** [comment] 2022-03-06 05:07
> No, this has already been reported, and if you look at the issue I linked, it's still open and assigned to the upcoming 2.6.4 update.

Ok, Thanks
