### ISSUE TITLE
Server sent invalid packet

### ISSUE THREAD

**Issue by Shashamove** [ReplayMod/ReplayMod#787] opened 2022-11-04 13:35 UTC
Literally after recording a replay on a minehut server, it does this. Its only on minehut though
![Screenshot_155](https://user-images.githubusercontent.com/96913678/199985419-9e073cbc-9c17-4dcc-998d-d13e262bfc39.png)

**Comment by RaderRMT** [comment] 2022-11-04 13:36
disable the chat in the ReplayMod settings

**Comment by Johni0702** [comment] 2022-11-05 09:00
Could you please attach one such replay, so I can try to reproduce it on my machine and then debug it?

**Comment by la-jig** [comment] 2022-11-13 18:09
Same
For me all my replays are affected

**Comment by la-jig** [comment] 2022-11-13 18:11
Your also not alone:
https://github.com/ReplayMod/ReplayMod/issues/789

**Comment by la-jig** [comment] 2022-11-13 18:50
If you have multiconnect mod, that mod is the issue

**Comment by Johni0702** [comment] 2022-12-06 12:01
Due to lack of details supplied by the OP, I'll assume this was indeed caused by the multiconnect incompatibility and will close this as a duplicate of #558.

**Closed by Johni0702** 2022-12-06 12:01 UTC
Labels: bug, needs more information
