### ISSUE TITLE
 Crash report, using forge with optifine and replaymod #645 

### ISSUE THREAD

**Issue by RikyRuggi** [ReplayMod/ReplayMod#571] opened 2021-08-21 12:41 UTC
I was trying to record some clips on servers.
Whenever i quit the server to save the file, it loads to 4% then i get this error:
[error.txt](https://github.com/ReplayMod/ReplayMod/files/7025516/error.txt)

Note: in single player it doesnt happen

**Comment by Johni0702** [comment] 2021-08-21 12:45
Duplicate of #568

**Closed by Johni0702** 2021-08-21 12:45 UTC
