### ISSUE TITLE
Some replays randomly do not save on ReplayMod 1.8.9

### ISSUE THREAD

**Issue by EPICSAURUSS** [ReplayMod/ReplayMod#220] opened 2020-06-10 19:49 UTC
Today, I tried using replaymod and discovered something quite odd. When I would join some servers such as MunchyMc and record a replay, it would save perfectly fine. But when I replay on servers such as Hypixel or Syuu, it gives me the following error https://pastebin.com/ibUVzt5H

I am using the latest version of replaymod for minecraft 1.8.9. The only other mods I used other than replaymod were Optifine and OrangeMarshall's animations mod and toggle sprint mod. Yes, I do have ffmpeg installed.

**Comment by Johni0702** [comment] 2020-06-21 14:23
Duplicate of #210

**Closed by Johni0702** 2020-06-21 14:23 UTC
