### ISSUE TITLE
Trying to apply Start/Stop/Pause/Resume cuts causes crash

### ISSUE THREAD

**Issue by TyLockhart** [ReplayMod/ReplayMod#549] opened 2021-07-23 00:12 UTC
Crash report:

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 22/07/21 7:36 PM
Description: Running marker processor

io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:100)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:84)
	at com.replaymod.replaystudio.io.ReplayOutputStream.doWrite(ReplayOutputStream.java:166)
	at com.replaymod.replaystudio.io.ReplayOutputStream.write(ReplayOutputStream.java:146)
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:193)
	at com.replaymod.editor.gui.GuiEditReplay.lambda$apply$10(GuiEditReplay.java:158)
	at com.replaymod.editor.gui.GuiEditReplay$$Lambda$3424/892096889.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8566713000 bytes (8169 MB) / 9361686528 bytes (8928 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.16.5_HD_U_G6
	OptiFine Build: 20210117-013236
	Render Distance Chunks: 11
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 461.72
	OpenGlRenderer: GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.5
	OptiFine jar version: OptiFine_1.16.5_HD_U_G6
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:\Users\Win10\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G6\Optifine-mapped.jar
	OptiFabric error: <None>
	

![javaw_LwwJPF9jXz](https://user-images.githubusercontent.com/53748468/126723290-8de27e96-74aa-4b3e-99df-0d2a40be148c.png)

All cuts were created in-game, clicked start recording, pause/resume until the end where I clicked stop recording and left the game
Deleted my old 1.16.4 replaymod jar file after trying to apply cuts
Installed newest version of replaymod and tried applying cuts with different amounts of RAM, always crashes at 59%
I have tried to find similar issues across the archived forum, discord and github - went through a heap but nothing seems to help my issue, will continue looking after posting here
Tried asking in discord: was told to just not use cuts in the first place, very helpful tool though, would like to keep using

**Comment by Johni0702** [comment] 2021-07-23 05:09
Duplicate of #492

**Closed by Johni0702** 2021-07-23 05:09 UTC
