### ISSUE TITLE
crash during replay if LittleTiles gui was used

### ISSUE THREAD

**Issue by Resuz** [ReplayMod/ReplayMod#30] opened 2018-05-21 14:38 UTC
https://github.com/CreativeMD/LittleTiles/issues/87
steps to reproduce:
play your world (with recording enabled)
open Little chisel gui
exit world
play just recored replay
When it goes to the moment when gui was oppened it will crash.

I see that this is most likely a LT specific issue, but its author said that he aren't going to fix this (because he has no idea how Replay mod works), so would be nice if you could do so.

**Comment by Resuz** [comment] 2018-05-21 14:39
[crash-2018-05-20_02.39.18-client.txt](https://github.com/ReplayMod/ReplayMod/files/2022955/crash-2018-05-20_02.39.18-client.txt)

**Comment by Johni0702** [comment] 2018-05-28 12:14
Yeah, this looks very much like an issue with LT. I've explained the workings of the RM and probable causes over on their issue.
Closing this as there's almost certainly nothing we can do on our end to fix this (unless it turns out the issue isn't with LT).

**Closed by Johni0702** 2018-05-28 12:14 UTC
