### ISSUE TITLE
Buggy rendering 

### ISSUE THREAD

**Issue by minomy13** [ReplayMod/ReplayMod#604] opened 2021-11-07 10:34 UTC

**Comment by minomy13** [comment] 2021-11-07 10:35
<img width="1017" alt="Bildschirmfoto 2021-11-07 um 11 34 54" src="https://user-images.githubusercontent.com/61352736/140641463-701f5bba-e4ad-4d52-85e9-29d9127365ca.png">

**Comment by RaderRMT** [comment] 2021-11-07 10:37
that's a known issue with retina displays. it shouldn't affect the final render

**Comment by Johni0702** [comment] 2021-11-07 10:41
Duplicate of #338

**Closed by Johni0702** 2021-11-07 10:41 UTC
