### ISSUE TITLE
Creating folders option

### ISSUE THREAD

**Issue by TiboOpGithub** [ReplayMod/ReplayMod#648] opened 2022-01-01 20:09 UTC
An option for creating folders in replay viewer in which you can put certain replays per project. As this mod does for resource packs. (Unfortunately this mod is not for news releases :/). https://www.curseforge.com/minecraft/mc-mods/resource-pack-organizer

**Comment by Johni0702** [comment] 2022-01-01 20:10
Duplicate of #320

**Closed by Johni0702** 2022-01-01 20:10 UTC
