### ISSUE TITLE
MixinTransformerError: An unexpected critical error was encountered

### ISSUE THREAD

**Issue by CrushedPixel** [ReplayMod/ReplayMod#177] opened 2020-05-14 23:55 UTC
[crash-2020-05-14_20.45.37-client.txt](https://github.com/ReplayMod/ReplayMod/files/4631582/crash-2020-05-14_20.45.37-client.txt)

Could this be caused by an old Fabric (API?) version?

**Comment by Johni0702** [comment] 2020-05-15 08:02
In general, yes, could be caused by old fabric loader, old fabric api, old optifabric or old optifine, don't see how it would be caused by RM though.
Most likely a mismatch between fabric api and optifabric.

**Comment by Johni0702** [comment] 2020-05-23 18:33
Closing cause outdated RM and other mods.

**Closed by Johni0702** 2020-05-23 18:33 UTC
