### ISSUE TITLE
[Bug] Chunks that already loaded before recording not showing in replay

### ISSUE THREAD

**Issue by i0xHeX** [ReplayMod/ReplayMod#139] opened 2020-04-23 14:53 UTC
**Steps to reproduce:**

1. Set `Automatic Recording` to `OFF`
2. Join the server, let chunks around you to load
3. Start recording
4. Fly around to load new chunks
5. Stop recording

**Expected behavior:**
When viewing replay, starting position around player should be loaded (chunks should be visible)

**Unexpected behavior:**
No chunks visible around starting player position, only new he loaded during recording.
https://i.imgur.com/9l4yv0E.png

P.S. Reloading chunks with `F3 + A` during recording does not help.

**Info:**
- Windows 10 x64
- Java 14 (OpenJDK)
- Replay Mod 2.3.0 b1 (1.15.2)

**Other Mods:**
- fabric-api-0.5.1+build.294-1.15
- optifabric-1.0.0-beta8
- OptiFine_1.15.2_HD_U_G1_pre13_MOD

**Comment by Johni0702** [comment] 2020-05-08 08:00
Cannot reproduce:
![](https://i.johni0702.de/TZPnQ.png)

I also don't see the player entity in your screenshot. Does it not render either?
Also, it seems like you're at about 50% of your replay, so right somewhere in the middle of `4. Fly around to load new chunks`, so not seeing chunks at the place where the player spawned (i.e. where they no longer are) would be expected.

If this only happens with `Automatic Recording` disabled, then an easy way for me to reproduce it is for you to send me the replay and the similarly named replay from `.minecraft/replay_recordings/raw/` (that's the full replay, without the automatic recording changes applied). That way the difference would be obvious (and I could also verify any potential fix).

**Comment by i0xHeX** [comment] 2020-05-08 16:39
Screenshot is a moment a bit later when I was flying and loaded few new chunks. At first position you see nothing loaded except your player, who moves around (but some move animations are broken due to no terrain).

I tried to reproduce that again with same version when I posted this (2.3.0-b1) (also with more mods including prev but seems this does not matter here) and got a bit another situation. Now some of the chunks are visible and some not in the recording. Demo:
https://youtu.be/qXa-jTxwXDU
And recordings (everything that were added to folder since it was empty): 
[replay_recordings.zip](https://github.com/ReplayMod/ReplayMod/files/4600290/replay_recordings.zip)

I also reproduced this on new version (2.3.0):
https://youtu.be/OfyvrRNOwkg
[replay_recordings_1.zip](https://github.com/ReplayMod/ReplayMod/files/4600331/replay_recordings_1.zip)

**Comment by LindaJuffermans** [comment] 2021-03-03 16:11
There is new evidence that this is not resolved with ReplayMod-1.6.4-2.5.2:

[Missing-Chunks-Raw-Recording.mcpr](https://github.com/ReplayMod/ReplayMod/files/6077360/Missing-Chunks-Raw-Recording.zip)
(original name lost due to breiz.mp file transfer, renamed to .zip for github)

**Comment by Johni0702** [comment] 2021-03-03 16:15
@LindaJuffermans This particular issue has definitely been fixed with 2.5.2 and cannot possibly happen on an vanilla server (or single player). Please always open a separate issue unless you are certain that it is the same bug.

**Closed by Johni0702** 2021-03-03 16:15 UTC
Labels: bug
