### ISSUE TITLE
reply mod doesn't support Sodium ?!

### ISSUE THREAD

**Issue by Rebilium** [ReplayMod/ReplayMod#332] opened 2020-08-14 13:07 UTC
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/14/20 4:06 PM
Description: Rendering video

java.lang.UnsupportedOperationException: Rendering is not currently supported while Sodium is installed.
See https://github.com/ReplayMod/ReplayMod/issues/150
For now, you need to uninstall Sodium before rendering!
	at com.replaymod.render.hooks.ChunkLoadingRenderGlobal.install(ChunkLoadingRenderGlobal.java:68)
	at com.replaymod.render.hooks.ChunkLoadingRenderGlobal.<init>(ChunkLoadingRenderGlobal.java:58)
	at com.replaymod.render.rendering.VideoRenderer.setup(VideoRenderer.java:339)
	at com.replaymod.render.rendering.VideoRenderer.renderVideo(VideoRenderer.java:142)
	at com.replaymod.render.gui.GuiRenderSettings$8.run(GuiRenderSettings.java:243)
	at com.replaymod.core.ReplayMod.lambda$runLater$6(ReplayMod.java:541)
	at com.replaymod.core.ReplayMod$$Lambda$2449/861885296.run(Unknown Source)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at com.replaymod.core.ReplayMod$ReplayModExecutor.method_5383(ReplayMod.java:503)
	at com.replaymod.replay.InputReplayTimer.method_1658(InputReplayTimer.java:81)
	at com.replaymod.pathing.player.ReplayTimer.method_1658(ReplayTimer.java:47)
	at net.minecraft.class_310.method_1523(class_310.java:985)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 743675776 bytes (709 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		carpet: Carpet Mod in Fabric 1.4.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v2 4.5.0-unstable
		colormatic: Colormatic 2.2.2+mc.1.16.1
		connected_block_textures: Connected Block Textures 0.1.1+1.16
		fabric: Fabric API 0.16.0+build.384-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c02
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.0+55e0cc5f02
		fabricloader: Fabric Loader 0.9.0+build.204
		lambdynlights: LambDynamicLights 1.2.2+1.16.1
		litematica: Litematica 0.0.0-dev.20200711.162756
		lithium: Lithium 0.5.1
		logical_zoom: Logical Zoom 0.0.4
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		minecraft: Minecraft 1.16.1
		minihud: MiniHUD 0.19.0-dev.20200701.005153
		modmenu: Mod Menu 1.14.5+build.30
		no_fog: No Fog 1.0.1-beta.1+1.16.1
		phosphor: Phosphor 0.6.0+build.7
		replaymod: Replay Mod 1.16.1-2.4.1
		sodium: Sodium 0.1.0
		spruceui: SpruceUI 1.5.8
		tweakeroo: Tweakeroo 0.10.0-dev.20200630.023405
		worldedit: WorldEdit 7.2.0-beta-02+d10d7d6

**Comment by Johni0702** [comment] 2020-08-14 14:10
Duplicate of #150

**Closed by Johni0702** 2020-08-14 14:10 UTC
