### ISSUE TITLE
An bug when loading .mcpr file

### ISSUE THREAD

**Issue by MorningXiao** [ReplayMod/ReplayMod#809] opened 2023-01-09 04:06 UTC
when i load a .mcpr file, it's always says
![image](https://user-images.githubusercontent.com/90488440/211239210-d52e92be-fcb7-4063-97ba-bed3c7be400f.png)
and raising an error
![image](https://user-images.githubusercontent.com/90488440/211239372-72b8a54e-db23-42fa-bea4-e8aceabd9661.png)
it seems like multiconnect's issue
when i disabled multiconnect, it can work correctly.
full log:[latest.log](https://github.com/ReplayMod/ReplayMod/files/10370308/latest.log)
minecraft version: fabric 1.19.2
replay version: 2.6.9
multiconnect version: 1.6-beta.23

**Comment by Felix14-v2** [comment] 2023-01-10 15:00
Known issue, see #558

**Comment by Johni0702** [comment] 2023-01-10 21:37
Duplicate of #558

**Closed by Johni0702** 2023-01-10 21:37 UTC
