### ISSUE TITLE
Replay mod crashes when I press the render button

### ISSUE THREAD

**Issue by LemTheAsian** [ReplayMod/ReplayMod#544] opened 2021-07-16 02:28 UTC
[crash-2021-07-16_12.22.37-client.txt](https://github.com/ReplayMod/ReplayMod/files/6827366/crash-2021-07-16_12.22.37-client.txt)

**Comment by Johni0702** [comment] 2021-07-16 09:38
Duplicate of #520

**Closed by Johni0702** 2021-07-16 09:38 UTC
