### ISSUE TITLE
Underwater is entirely blue and black

### ISSUE THREAD

**Issue by itsmorethantech** [ReplayMod/ReplayMod#732] opened 2022-05-14 08:34 UTC
![image](https://user-images.githubusercontent.com/82797019/168417759-d0b28e22-7253-4c83-830f-ac1bf337ff3d.png)
https://www.youtube.com/watch?v=JyNf0-0LsXI

(Mod pack is Fabulously Optimized with sodium disabled)

**Comment by Johni0702** [comment] 2022-05-17 04:29
What's your ReplayMod version?

**Comment by Johni0702** [comment] 2022-07-17 12:11
Duplicate of #572

**Closed by Johni0702** 2022-07-17 12:11 UTC
