### ISSUE TITLE
Replay crash error

### ISSUE THREAD

**Issue by Sebastrol** [ReplayMod/ReplayMod#230] opened 2020-06-19 15:32 UTC
**- Which ReplayMod version are you using?** Replay Mod 1.8.9 - 2.3.1
**- What did you do and what happened?** When finishing with recording any minigame on Hypixel Network, the replay doesn't get saved and it reveals this error message.

Screenshot of  the crash
![Screenshot_3](https://user-images.githubusercontent.com/67159540/85149947-34bbb280-b252-11ea-9bb0-dc38a49ff03d.png)

Raw footage
[2020_06_19_17_18_58.mcpr.cache.zip](https://github.com/ReplayMod/ReplayMod/files/4805418/2020_06_19_17_18_58.mcpr.cache.zip)

**Comment by Nemos59** [comment] 2020-06-19 15:48
use 2.1.4 and try again

**Comment by Sebastrol** [comment] 2020-06-19 15:59
> 
> 
> use 2.1.4 and try again

This fixed it thank you very much. Do you have an explanation for why this fixed it?

**Comment by Johni0702** [comment] 2020-06-21 14:23
Duplicate of #210

**Closed by Johni0702** 2020-06-21 14:23 UTC
