### ISSUE TITLE
Skin not visible in renders with RM 2.3.0

### ISSUE THREAD

**Issue by CrushedPixel** [ReplayMod/ReplayMod#169] opened 2020-05-11 18:08 UTC
OptiFine 1.9.0 HD U H5
Replay Mod v1.8.9-2.3.0
Forge1.8.9 - 11.15.1.2318 (the latest version of 1.8.9)

It is reported that skins show in the replay, but not in rendered videos.
This applies to all replays, but I still attached one.

[2020_05_10_02_27_15.mcpr.zip](https://github.com/ReplayMod/ReplayMod/files/4611238/2020_05_10_02_27_15.mcpr.zip)
[latest (4).log](https://github.com/ReplayMod/ReplayMod/files/4611300/latest.4.log)

**Comment by Johni0702** [comment] 2020-05-11 18:26
This has already been fixed in 2.3.0 (duplicate of #157) and the declared versions do not match with those in the log and the replay (both are -b1), so I'm assuming them to be incorrect.

**Closed by Johni0702** 2020-05-11 18:26 UTC

**Comment by CrushedPixel** [comment] 2020-05-11 18:29
Thank you, I got the wrong info from the tester then. My bad for not double-checking!
