### ISSUE TITLE
Server Sent Invalid packet error when loading replay file

### ISSUE THREAD

**Issue by la-jig** [ReplayMod/ReplayMod#792] opened 2022-11-13 17:32 UTC
I'm trying to load a replay mod file but when I do: I get errors saying "Server Sent Invalid Packet", my fabric version is 0.14.9 here's my logs:
`
// Github won't let me submit too big of a log
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: java.util.NoSuchElementException: encoder
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at net.minecraft.class_2535.handler$bog000$onSetProtocol(class_2535.java:1053)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at net.minecraft.class_2535.method_10750(class_2535.java)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at net.minecraft.class_635.method_12588(class_635.java:136)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at net.minecraft.class_2901.method_12594(class_2901.java:25)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at net.minecraft.class_2901.method_11054(class_2901.java:7)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at net.minecraft.class_2535.method_10759(class_2535.java:167)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at net.minecraft.class_2535.method_10770(class_2535.java:152)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at com.replaymod.replay.ReplayHandler$1.channelRead0(ReplayHandler.java:264)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at com.replaymod.replay.FullReplaySender.channelRead(FullReplaySender.java:418)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at com.replaymod.replay.FullReplaySender$2.run(FullReplaySender.java:1031)
[12:32:03] [replaymod-async-sender/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[12:32:03] [replaymod-async-sender/ERROR]: Received class net.minecraft.class_2658 that couldn't be processed
java.lang.ClassCastException: class net.minecraft.class_635 cannot be cast to class net.minecraft.class_2602 (net.minecraft.class_635 and net.minecraft.class_2602 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @282003e1)
	at net.minecraft.class_2658.method_11054(class_2658.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:167) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:152) [client-intermediary.jar:?]
	at com.replaymod.replay.ReplayHandler$1.channelRead0(ReplayHandler.java:264) [replaymod-1.19.1-2.6.8.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) [netty-transport-4.1.77.Final.jar:?]
	at com.replaymod.replay.FullReplaySender.channelRead(FullReplaySender.java:418) [replaymod-1.19.1-2.6.8.jar:?]
	at com.replaymod.replay.FullReplaySender$2.run(FullReplaySender.java:1031) [replaymod-1.19.1-2.6.8.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

`

Here's my installed mods:
`Adorn, Cloth Config v8, Collective (Fabric), ConnectedTexturesMod for Fabric, Double Doors (Fabric), EasyAutoCrafting, Exline's Furniture, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Language Kotlin, Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Inventory Profiles Next, Iris, LazyDFU, Litematica, Lithium, MaLiLib, Mod Menu, MultiConnect, MultiConnect API, No Chat Reports, Replay Mod, Robin Hood, Roughly Enough Items, Sodium, WorldEdit, Xaero's Minimap`

Can someone help?

**Comment by la-jig** [comment] 2022-11-13 17:34
Also every mcpr file doesn't load and gives "Server Sent Invalid Packet"

**Comment by la-jig** [comment] 2022-11-13 17:45
Also the screenshot of what's inside the gui when the error happens:
![Screen Shot 2022-11-13 at 12 24 23 PM](https://user-images.githubusercontent.com/82725076/201536281-0f1d2a0b-fb7d-485a-954b-a3c69a62b0bb.png)

**Comment by Johni0702** [comment] 2022-11-14 07:13
Duplicate of #558

**Closed by Johni0702** 2022-11-14 07:13 UTC

**Comment by la-jig** [comment] 2022-11-14 07:27
That's what I discovered
