### ISSUE TITLE
ReplayMod doesn't load in 1.8.9 with 5zig or NickHider

### ISSUE THREAD

**Issue by LaniJW** [ReplayMod/ReplayMod#184] opened 2020-05-21 11:03 UTC
Possibly related to #181.

[latest.log](https://github.com/ReplayMod/ReplayMod/files/4662061/latest.log)
Mod Jars: https://mega.nz/folder/j7RBnaRD#MU-WL8ATpC0-OWz7GbaszQ

**Comment by CrushedPixel** [comment] 2020-05-21 11:43
To work around this issue, try renaming the ReplayMod jar to `0aaaReplayMod.jar` - this causes the ReplayMod to be loaded before other mods with Mixins.

**Comment by LaniJW** [comment] 2020-05-21 13:44
Thanks. Works for me.

**Comment by Johni0702** [comment] 2020-05-21 13:50
Duplicate of #181

**Closed by Johni0702** 2020-05-21 13:50 UTC
