### ISSUE TITLE
Game crashes when typing in the renaming replay section in the top-right "saving replay file..." window after leaving a world.

### ISSUE THREAD

**Issue by WalleyeGuy8371** [ReplayMod/ReplayMod#659] opened 2022-01-16 02:27 UTC
Video of the crash occurring.
https://user-images.githubusercontent.com/97816037/149644947-8a4e6c74-fec2-45d0-b4bf-e99754c6ff5a.mp4

**Comment by Kepler-17c** [comment] 2022-01-16 02:39
Please use the official Discord at https://discord.gg/5GR7RSb for support.

What other mods do you use?

**Comment by Johni0702** [comment] 2022-01-16 07:07
Duplicate of #635

**Closed by Johni0702** 2022-01-16 07:07 UTC
