### ISSUE TITLE
Game crashes whenever I try to rewind to start.

### ISSUE THREAD

**Issue by thesidekickpenguin** [ReplayMod/ReplayMod#387] opened 2020-10-10 04:22 UTC
Whenever I'm trying to edit a replay, and I put the little yellow thing at the start (new to replay mod, sorry) it just straight up crashes my game.
Here's the error code: 
The game crashed whilst calling gui method
Error: java.lang.NullPointerException: Calling Gui method
Exit Code: -1
If anyone could help that would be wondrous!

**Comment by Johni0702** [comment] 2020-10-10 08:32
Duplicate of #227

Seems to be a rare bug happening to only a few people. As a workaround you can enable Quick Mode (`Q` by default) and only disable it when you render you video.

**Closed by Johni0702** 2020-10-10 08:32 UTC

**Comment by thesidekickpenguin** [comment] 2020-10-11 21:42
> Duplicate of #227
> 
> Seems to be a rare bug happening to only a few people. As a workaround you can enable Quick Mode (`Q` by default) and only disable it when you render you video.
But I'm using 1.8.9 and Quick Mode dosen't work in that version.

**Comment by Johni0702** [comment] 2020-10-11 21:47
> But I'm using 1.8.9 and Quick Mode dosen't work in that version.

In that case, you'll either have to update to a modern version of Minecraft or just live with the bug (i.e. try to avoid rewinding at all costs) until it is fixed. I'm not aware of any other workaround.
