### ISSUE TITLE
How can you join 2 replays together?

### ISSUE THREAD

**Issue by ErrorBot1122** [ReplayMod/ReplayMod#591] opened 2021-09-30 16:17 UTC
how do you do that because [forms](https://www.replaymod.com/forum/thread/667) did not show me how to do it.

**Comment by RaderRMT** [comment] 2021-09-30 16:26
you can't

**Comment by Johni0702** [comment] 2021-09-30 18:58
Duplicate of #554

**Closed by Johni0702** 2021-09-30 18:58 UTC

**Comment by ErrorBot1122** [comment] 2021-09-30 21:07
A better version of this same issue/question: #592
