### ISSUE TITLE
renderQueue.json broken after copy timeline

### ISSUE THREAD

**Issue by LindaJuffermans** [ReplayMod/ReplayMod#495] opened 2021-03-26 16:21 UTC
ReplayMod-1.16.4-2.5.2 with Minecraft 1.16.5

After using copy on the keyframe repository, the recording becomes unavailable in the Replay Viewer.
Issue is resolved by removing renderQueue.json from the mcpr file.

[latest.log when opening the Replay Viewer](https://github.com/ReplayMod/ReplayMod/files/6213069/latest.log)
[00_-_Breaks_glass_.mcpr](https://github.com/ReplayMod/ReplayMod/files/6213076/00_-_Breaks_glass_.zip)

**Comment by Johni0702** [comment] 2021-03-26 17:16
I highly doubt this is actually related to the Copy button.
From the crash this looks like an issue with deserializing the render jobs when chroma keying has been enabled.

**Comment by Johni0702** [comment] 2021-08-15 09:29
Duplicate of #564

**Closed by Johni0702** 2021-08-15 09:29 UTC
Labels: bug
