### ISSUE TITLE
Not rendering more than ~10 blocks

### ISSUE THREAD

**Issue by OscarleBG** [ReplayMod/ReplayMod#151] opened 2020-05-01 02:14 UTC
I tried to make some recordings in solo and in servers, my render distance alway being at least 15 chuncks, and when I check the recordings in the recording viewer, it wont render more than ~10 blocks. I'm playing on my mac I7 16go of ram with macos.

**Comment by Johni0702** [comment] 2020-05-01 21:59
Minecraft version?
ReplayMod version?
Optifine? (if so, version?)
Any other mods?
Does this happen 100% reliable, even if you just join a new SP flat world, quit and then view that replay?
Do entities render outside of those ~10 blocks distance?

A screenshot of the ~10 blocks could show something interesting which you didn't notice.

**Comment by OscarleBG** [comment] 2020-05-03 21:33
1.15.2
lastest
no, I tried but I failed haha
nope
yes
yes

Without rendering:
![Capture d’écran 2020-05-04 à 05 29 28](https://user-images.githubusercontent.com/54399962/80926269-c9647100-8dc8-11ea-840e-a296e60283e1.png)

After rendering:
![vlcsnap-2020-05-04-05h31m21s762](https://user-images.githubusercontent.com/54399962/80926262-b6ea3780-8dc8-11ea-8b84-92b00d1cbb2b.png)

**Comment by Johni0702** [comment] 2020-05-03 21:48
Could you also grab a quick screenshot of a newly created flat world in the replay viewer (similar camera angle)?
Can't really see any pattern in the missing chunks if most of them are missing by design of the map.

FTR: "latest" at time of writing is 1.15.2-2.3.0-b1

**Comment by OscarleBG** [comment] 2020-05-03 22:05
Oh uhmm, that's embarrassing, on a flat world, the problem doesn,t appear. It's weird because on the server I'm playing, I set the render distance of a player to 30 chunks or something...

**Comment by Johni0702** [comment] 2020-05-03 22:23
It's probably to do with the skyblock kind of map then. Could you send me one of your affected replays?
I'll see if i can figure out the issue when I've got time to do so but for that I'll have to be able to reproduce it.

**Comment by OscarleBG** [comment] 2020-05-03 22:31
Here you go: 
[2020_04_29_16_02_48_1.mcpr.zip](https://github.com/ReplayMod/ReplayMod/files/4572059/2020_04_29_16_02_48_1.mcpr.zip)

**Comment by Johni0702** [comment] 2020-05-07 15:55
@OscarleBG 
Thanks for the replay! I've tracked down the issue to likely be caused by a bug in the Start/Stop/Pause/Resume feature.
To further debug this (and confirm that it's fixed once I'm at that point), the uncut replay file would be immensely helpful. You should be able to find it at `.minecraft/replay_recordings/raw/2020_04_29_16_02_48.mcpr`.

**Comment by Johni0702** [comment] 2020-05-08 09:47
Update:
I was able to create a replay which exhibits the same issue by creating a world with "Void" preset, disabling auto-recording, entering the world, starting recording, placing a few blocks (don't think that was necessary) and then exiting the world.

**Closed** 2020-05-08 10:30 UTC
