### ISSUE TITLE
Extra skin layers not visible during replay

### ISSUE THREAD

**Issue by Johni0702** [ReplayMod/ReplayMod#118] opened 2020-04-02 16:09 UTC
replaymod-1.15.2-2.2.0-b7-43-g065d713.jar

> one issue I'm seeing is it isn't rendering extra skin layers on my character

**Comment by LogicalGeekBoy** [comment] 2020-04-02 16:34
For some added context, this only seems to happen when playing on a server. I tested on a single player world and it rendered just fine. When connecting to a multi-player server the replay was recorded by the additional layers to my skin where not visible in the editor. The server is a paper/spigot server if that makes any difference. I tried this without any other mods and the problem remains.

**Comment by LogicalGeekBoy** [comment] 2020-04-02 16:58
After some more testing this seems to be intermittent. The test I just did on the same server is working fine and my skin layers are appearing. I'll keep an eye on it and we report how often I see it.

**Comment by Xanton19** [comment] 2020-04-02 18:32
Wow, Johni0702, I am very impressed that you made a playable 1.15 version of Replaymod in a short timeframe, I really appreciate it, thank you very much!

I don't want to bother or overwhelm you with bugs, that have been discovered, as it is expected with early versions.

Now the Bugs I have encountered in the 1.15.2 Version until now are:

1. Invisible Entities show up in the Replay, even they are not supposed to be there (For example Invisible Armour Stands show up in the Mineplex lobby)
![Screenshot (18565)](https://user-images.githubusercontent.com/40340770/78284386-9dcb3e00-751f-11ea-98ff-ae8d8c114c51.png)

2. Strange Text character always appears at the end of the text line
![Screenshot (18567)](https://user-images.githubusercontent.com/40340770/78284629-01ee0200-7520-11ea-9f68-4f274a827b9d.png)
![Screenshot (18562)](https://user-images.githubusercontent.com/40340770/78283542-3791eb80-751e-11ea-897d-97d7a1e6ea04.png)

3. As you have mentioned in the closing of my "1.15 Compiling Failed" thread, Optifine is incompatible with the Replaymod

My compiled Replaymod 1.15 jar (Needed to compress it to zip, as Github doesn't support uploading jar files and I know that a jar file is a zip compressed file, I just don't want to make things complicated): [replaymod-1.15.2-2.2.0-b7-43-g065d713.jar.zip](https://github.com/ReplayMod/ReplayMod/files/4422934/replaymod-1.15.2-2.2.0-b7-43-g065d713.jar.zip)


An issue I have encountered with the 1.14.4 version of Replaymod and [Worlddownloader for Fabric](https://github.com/gamax92/WorldDownloader-Fabric/releases) is that it crashes when I download the world from a replay for example.

**Comment by LogicalGeekBoy** [comment] 2020-04-03 10:55
This seems to be an issue 50% of the time. I've tried to work out why it works sometimes and not others but I haven't been able to reproduce it reliably but it's a probably that happens a lot for me currently.

**Closed** 2020-04-09 16:39 UTC
Labels: 1.15, bug
