### ISSUE TITLE
Game crash when launching

### ISSUE THREAD

**Issue by UrLxrd** [ReplayMod/ReplayMod#175] opened 2020-05-13 21:36 UTC
I'm using the 2.3.0 version of replay mod for Minecraft 1.14.4, my game won't launch because "Could not execute entrypoint stage 'client' due to errors, provided by 'replaymod'!".
I expected the game to launch.
[crash-2020-05-13_23.34.13-client.txt](https://github.com/ReplayMod/ReplayMod/files/4624828/crash-2020-05-13_23.34.13-client.txt)

**Comment by CrushedPixel** [comment] 2020-05-13 22:11
This is a duplicate of https://github.com/ReplayMod/ReplayMod/issues/162
In the meantime, you can either use ReplayMod 2.2.0-b7 or remove Optifine.

**Closed by CrushedPixel** 2020-05-13 22:11 UTC
