### ISSUE TITLE
Rendering problem.

### ISSUE THREAD

**Issue by WolfgangProh** [ReplayMod/ReplayMod#228] opened 2020-06-17 15:59 UTC
So, I am new to replaymod and wanted to make a edit. Everything works fine, till I get to rendering the video. I click on rendering, but nothing happens... I even hear the sound of the rendering button, but nothing happens. Maybe my settings are wrong or something like that. But I haven't found the issue.

**Comment by Nemos59** [comment] 2020-06-17 17:13
possible duplicate of #206

**Comment by Johni0702** [comment] 2020-06-17 17:58
Duplicate of #206

**Closed by Johni0702** 2020-06-17 17:58 UTC
