### ISSUE TITLE
Client Freeze

### ISSUE THREAD

**Issue by MopsTMC** [ReplayMod/ReplayMod#480] opened 2021-02-21 17:49 UTC
Hello, today I tried using ReplayMod alongside some other mods on my client. The moment I try loading or generating a world the game freezes completely on the loading animation and the console prints out these errors, the latter one being spammed tens of times resulting in a huge log file. At that point there is nothing else to do other than killing the process because it doesn't crash, it just freezes.
```[13:30:22] [main/ERROR]: Writing packet:
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@44704ce8 rejected from java.util.concurrent.ThreadPoolExecutor@2ff71ec[Shutting down, pool size = 1, active threads = 1, queued tasks = 2, completed tasks = 0]
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.4) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.AbstractExecutorService.submit(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Unknown Source) ~[?:1.8.0_281]
	at com.replaymod.recording.packet.PacketListener.save(PacketListener.java:202) ~[replaymod-1.16.4-2.5.2.jar:?]
	at com.replaymod.recording.packet.PacketListener.lambda$save$1(PacketListener.java:167) ~[replaymod-1.16.4-2.5.2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:103) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1015) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:215) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
[13:30:22] [main/ERROR]: Writing packet:
java.io.IOException: Unknown packet type:class net.minecraft.class_2658
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.4) ~[?:?]
	at com.replaymod.recording.packet.PacketListener.getPacketData(PacketListener.java:461) ~[replaymod-1.16.4-2.5.2.jar:?]
	at com.replaymod.recording.packet.PacketListener.save(PacketListener.java:201) ~[replaymod-1.16.4-2.5.2.jar:?]
	at com.replaymod.recording.packet.PacketListener.lambda$save$1(PacketListener.java:167) ~[replaymod-1.16.4-2.5.2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:103) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1015) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:215) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
```
I use the following mods:
- CameraOverhaul-1.2.2-fabric-universal.jar
- ChatEmotes-v1.1-Fabric-1.16.jar
- DamageTilt-1.16-fabric-0.1.2.jar
- DynamicSoundFilters-1.2.0+1.16.5.jar
- FallingTree-Fabric-1.16.5-2.10.2.jar
- Mc122477Fix-fabric-mc1.16.jar
- Missing+Bits-v1.16.3+Fabric+b1.jar
- OfflineSkins-1.16.5-v1-fabric.jar
- PresenceFootsteps-r29+1.16.4.jar
- TRansliterationLib-1.0.2.jar
- antiqueatlas-5.4.4-fabric.jar
- armor-visibility-1.0.1.jar
- atmosfera-1.3.5.jar
- autoconfig1u-3.3.1.jar
- bedspreads-fabric-1.3.1-1.16.4.jar
- beenfo-1.16.5-fabric0.30.0-1.3.jar
- better-end-0.9.1-pre.jar
- better-nether-5.0.7.jar
- betterf3-1.1.2+1.16.2.jar
- chat_heads-0.2.1+1.16.2.jar
- cinderscapes-1.3.3.jar
- cloth-config-4.11.14-fabric.jar
- connectiblechains-1.1.0.jar
- cullleaves-2.0.0.jar
- custom-stars-0.4.1.jar
- dehydration-1.0.8.jar
- dynamic-fps-2.0.1.jar
- enhanced_attack_indicator-1.0.0+1.16.jar
- environmentz-1.0.10.jar
- fabric-api-0.30.3+1.16.jar
- fabric-language-kotlin-1.4.30+build.2.jar
- fabrishot-1.2.3.1.jar
- fallingleaves-1.5.0+1.16.5.jar
- fast-chest-1.0.jar
- hatlist-1.1.jar
- helpfulhitboxes-fabric-1.0.0.jar
- horse-stats-vanilla-4.1.4.jar
- howlingwolves-1.0.0+build.1.jar
- immersive-portals-0.78-mc1.16.5-fabric.jar
- item-model-fix-1.0.0.jar
- lambdynamiclights-fabric-1.3.4+1.16.jar
- lazydfu-0.1.2.jar
- lithium-fabric-mc1.16.5-0.6.3.jar
- microDurability-0.3.0+1.16.3.jar
- modmenu-1.16.7.jar
- nicephore-fabric-1.16.x-1.1.2.jar
- nostrip-1.2.0-1.16.2+.jar
- notenoughanimations-1.1.0.jar
- notenoughcrashes-3.1.5-fabric.jar
- now-playing-1.1.4-fat.jar
- okzoomer-4.0.1+1.16.2.jar
- onsoulfire-1.16.5-1.jar
- passable-leaves-1.2.3.jar
- phosphor-fabric-mc1.16.3-0.7.1+build.11.jar
- pumice-0.0.2.jar
- randompatches-2.4.3-fabric.jar
- repurposed_structures-1.16.5-1.8.1.jar
- rocks-1.3.1.jar
- seamless-loading-screen-1.3.1+1.16.2.jar
- seasons-1.0.3-BETA.jar
- sheepconsistency-1.0.2.jar
- shulkerboxtooltip-2.3.5+1.16.5.jar
- signcopy-1.0.jar
- simple-utilities-mod-2.1.1.jar
- smoke-suppression-1.0+MC1.16.2-1.16.5.jar
- sodium-fabric-mc1.16.4-0.1.1-ipc2.jar
- splash-1.2.0.jar
- terrestria-2.2.0.jar
- tooltipfix-1.0.2-1.16.jar
- traverse-3.3.2.jar
- unearthed-1.1.0.jar
- vt-downloader-1.0.3.jar
- woodcutter-1.2-1.16.1.jar

**Comment by Johni0702** [comment] 2021-02-21 18:57
Please attach the full `.minecraft/logs/latest.log` file, there is likely a different, more important error preceding these two.
Also, could you try narrowing down the list of mods by throwing out half of them at a time?

**Comment by MopsTMC** [comment] 2021-02-21 22:12
Ok, I will be doing that tomorrow as it might take some time.

**Comment by MopsTMC** [comment] 2021-02-22 16:35
Ok, so I have narrowed it down to the [MissingBits](https://www.curseforge.com/minecraft/mc-mods/missingbits) mod. Here's the logfile:
[latest.log](https://github.com/ReplayMod/ReplayMod/files/6023487/latest.log)

**Comment by Johni0702** [comment] 2021-08-15 11:38
Looks like this was fixed in fabric-api. I can reproduce it with 0.29.1 but not with 0.31.0.
Afaict this isn't even directly related to the ReplayMod, it's likely just a race condition and RM merely changes how long some things take.

**Closed by Johni0702** 2021-08-15 11:38 UTC
Labels: bug
